const BabyBaluga = [
	'[Verse 1]',
	'Baby beluga in the deep blue sea',
	'Swim so wild and you swim so free',
	'Heaven above and the sea below',
	'And a little white whale on the go',
	'',
	'[Chorus]',
	'Baby beluga, baby beluga',
	'Is the water warm',
	'Is your mama home with you, so happy',
	'',
	'[Verse 2]',
	'Way down yonder where the dolphins play',
	'Where you dive and splash all day',
	'Waves roll in and the waves roll out',
	"See the water squirtin' out of your spout",
	'',
	'[Chorus]',
	'Baby beluga, oh, baby beluga',
	'Sing your little song',
	'Sing for all your friends, we like to hear you',
	'',
	'[Verse 3]',
	"When it's dark, you're home and fed",
	'Curl up, snug in your water bed',
	'Moon is shining and the stars are out',
	'Good night, little whale, good night',
	'',
	'[Chorus]',
	'Baby beluga, oh, baby beluga',
	"With tomorrow's sun, another day's begun",
	"You'll soon be wakin'",
	'',
	'[Verse 4]',
	'Baby beluga in the deep blue sea',
	'Swim so wild and you swim so free',
	'Heaven above and the sea below',
	'And a little white whale on the go',
	"You're just a little white whale on the go",
];

export default BabyBaluga;
