const BlowinInTheWind = [
	'[Verses]',
	"There's two things I know for sure",
	'She was sent here from heaven',
	"And she's daddy's little girl",
	'As I drop to my knees by her bed at night',
	'She talks to Jesus',
	'And I close my eyes',
	'And I thank God for all of the joy in my life',
	'Oh, but most of all',
	'',
	'For butterfly kisses after bedtime prayer',
	'Sticking little white flowers all up in her hair',
	'"Walk beside the pony, Daddy, it\'s my first ride"',
	'"I know the cake looks funny, Daddy, but I sure tried"',
	"Oh, with all that I've done wrong",
	'I must have done something right',
	'To deserve a hug every morning',
	'And butterfly kisses at night',
	'',
	'Sweet 16 today',
	"She's looking like her mama",
	'A little more everyday',
	'One part woman',
	'The other part girl',
	'To perfume and make-up',
	'From ribbons and curls',
	'Trying her wings out in a great big world',
	'But I remember...',
	'',
	'Butterfly kisses after bedtime prayer',
	'Sticking little white flowers all up in her hair',
	'"You know how much I love you, Daddy, but if you don\'t mind"',
	'"I\'m only gonna kiss you on the cheek this time"',
	"Oh, with all that I've done wrong",
	'I must have done something right',
	'To deserve her love every morning',
	'And butterfly kisses at night',
	'',
	'Oh precious time',
	'Like the wind, the years go by',
	'Precious butterfly',
	'Spread your wings and fly',
	'',
	"She'll change her name today",
	"She'll make a promise",
	"And I'll give her away",
	'Standing in the bride-room',
	'Just staring at her',
	"She asked me what I'm thinking",
	'And I said, "I\'m not sure"',
	'"I just feel like I\'m losing my baby girl"',
	'And she leaned over',
	'',
	'Gave me butterfly kisses with her mama there',
	'Sticking little white flowers all up in her hair',
	'"Walk me down the aisle, Daddy, it\'s just about time"',
	'"Does my wedding gown look pretty, Daddy?"',
	'"Daddy, don\'t cry"',
	"Oh, with all that I've done wrong",
	'I must have done something right',
	'To deserve her love every morning',
	'And butterfly kisses',
	'',
	"I couldn't ask God for more",
	'Man, this is what love is',
	'I know I gotta let her go',
	"But I'll always remember",
	'Every hug in the morning',
	'And butterfly kisses',
];

export default BlowinInTheWind;
