const ClosingTimeChords = [
	'[Verse 1]',
	'Closing time,',
	'Open all the doors',
	'And let you out into the world',
	'Closing time,',
	'Turn all of the lights on',
	'Over every boy and every girl',
	'Closing time,',
	'One last call for alcohol',
	'',
	'So, finish your whiskey or beer',
	'Closing time,',
	"You don't have to go home",
	"But you can't stay here",
	'',
	'[Chorus]',
	'I know who I want to take me home',
	'I know who I want to take me home',
	'I know who I want to take me home',
	'Take me home',
	'',
	'[Verse 2]',
	'Closing time,',
	'Time for you to go out',
	'To the places you will be from',
	'Closing time,',
	"This room won't be open",
	'Till your brothers or your sisters come',
	'',
	'So, gather up your jackets, move it to the exits',
	'I hope you have found a friend',
	'Closing time,',
	'Every new beginning',
	"Comes from some other beginning's end, yeah",
	'',
	'[Chorus]',
	'I know who I want to take me home',
	'I know who I want to take me home',
	'I know who I want to take me home',
	'Take me home',
	'',
	'[Bridge]',
	'Closing time,',
	'Time for you to go out',
	'To the places you will be from',
	'',
	'[Chorus]',
	'I know who I want to take me home',
	'I know who I want to take me home',
	'I know who I want to take me home',
	'Take me home',
	'',
	'[Chorus]',
	'I know who I want to take me home',
	'I know who I want to take me home',
	'I know who I want to take me home',
	'Take me home',
	'',
	'Closing time,',
	'Every new beginning',
	"Comes from some other beginning's end",
];

export default ClosingTimeChords;
