const CountryRoads = [
	'[Verse 1]',
	'Almost heaven, West Virginia,',
	'Blue Ridge Mountains, Shenandoah River.',
	'Life is old there, older than the trees,',
	'Younger than the mountains, blowing like a breeze.',
	'',
	'[Chorus]',
	'Country roads, take me home to the place I belong.',
	'West Virginia, mountain mamma,',
	'Take me home, country roads.',
	'',
	'[Verse 2]',
	'All my memories gather round her,',
	"Miner's lady, stranger to blue water.",
	'Dark and dusty, painted on the sky,',
	'Misty taste of moonshine, teardrop in my eye.',
	'',
	'[Chorus]',
	'Country roads, take me home to the place I belong.',
	'West Virginia, mountain mamma,',
	'Take me home, country roads.',
	'',
	'[Bridge]',
	'I hear her voice in the morning hour, she calls me,',
	'The radio reminds me of my home far away.',
	'And driving down the road I get a feeling that I should have been home yesterday, yesterday.',
	'',
	'[Chorus]',
	'Country roads, take me home to the place I belong.',
	'West Virginia, mountain mamma,',
	'Take me home, country roads.',
	'',
	'Country roads, take me home to the place I belong.',
	'West Virginia, mountain mamma,',
	'Take me home, country roads',
	'',
	'Take me home now, country roads,',
	'Take me home now, country roads.',
];

export default CountryRoads;
