const HesGotTheWholeWorldInHisHands = [
	'[Verse]',
	"He's got the whole world in His hands",
	"He's got the whole world in His hands",
	"He's got the whole world in His hands",
	"He's got the whole world in His hands",
	'',
	'[Verse]',
	"He's got the wind and rain in His hands",
	"He's got the wind and rain in His hands",
	"He's got the wind and rain in His hands",
	"He's got the whole world in His hands",
	'',
	'[Verse]',
	"He's got the little tiny baby in his hands",
	"He's got the little tiny baby in his hands",
	"He's got the little tiny baby in his hands",
	"He's got the whole world in His hands",
	'',
	'[Verse]',
	"He's got you and me, brother, in his hands",
	"He's got you and me, brother, in his hands",
	"He's got you and me, brother, in his hands",
	"He's got the whole world in His hands",
	'',
	'[Verse]',
	"He's got you and me, sister, in his hands",
	"He's got you and me, sister, in his hands",
	"He's got you and me, sister, in his hands",
	"He's got the whole world in His hands",
	'',
	'[Verse]',
	"He's got everybody here, in his hands",
	"He's got everybody here, in his hands",
	"He's got everybody here, in his hands",
	"He's got the whole world in His hands",
];

export default HesGotTheWholeWorldInHisHands;
