const MichaelRowTheBoatAshore = [
	'Michael, row the boat ashore, hallelujah',
	'Michael, row the boat ashore, hallelujah',
	'Sister, help to trim the sail, hallelujah',
	'Sister, help to trim the sail, hallelujah',
	'',
	'The river is deep and the river is wide, hallelujah',
	'Green pastures on the other side, hallelujah',
	'',
	'Michael, row the boat ashore, hallelujah',
	'Michael, row the boat ashore, hallelujah',
	'Sister, help to trim the sail, hallelujah',
	'Sister, help to trim the sail, hallelujah',
	'',
	"Jordan's river is chilly and cold, hallelujah",
	'Chills the body but not the soul, hallelujah',
	'',
	'Michael, row the boat ashore, hallelujah',
	'Michael, row the boat ashore, hallelujah',
	'Sister, help to trim the sail, hallelujah',
	'Sister, help to trim the sail, hallelujah',
	'',
	'The river is deep and the river is wide, hallelujah',
	'Milk and honey on the other side, hallelujah',
	'',
	'Michael, row the boat ashore, hallelujah',
	'Michael, row the boat ashore, hallelujah',
	'Sister, help to trim the sail, hallelujah',
	'Sister, help to trim the sail, hallelujah',
];

export default MichaelRowTheBoatAshore;
