const TheCatCameBack = [
	'Sunshine go away today',
	"I don't feel much like dancing",
	"Some man's gone, he's tried to run my life",
	"Don't know what he's asking",
	'',
	"He tells me I'd better get in line",
	"Can't hear what he's saying",
	"When I grow up, I'm going to make it mine",
	"But these aren't dues I been paying",
	'',
	"How much does it cost, I'll buy it",
	"The time is all we've lost, I'll try it",
	"But he can't even run his own life",
	"I'll be damned if he'll run mine, Sunshine",
	'',
	'Sunshine go away today',
	"I don't feel much like dancing",
	"Some man's gone, he's tried to run my life",
	"Don't know what he's asking",
	'',
	'Working starts to make me wonder where',
	'The fruits of what I do are going',
	'He says in love and war all is fair',
	"But he's got cards he ain't showing",
	'',
	"How much does it cost, I'll buy it",
	"The time is all we've lost, I'll try it",
	"And he can't even run his own life",
	"I'll be damned if he'll run mine, Sunshine",
	'',
	'Sunshine come on back another day',
	"I promise you I'll be singing",
	"This old world, she's gonna turn around",
	"Brand new bells'll be ringing",
];

export default TheCatCameBack;
