const TieMeKangarooDownSport = [
	"There's an old Australian stockman lying, dying. He gets himself up",
	"onto one elbow and 'e turns to his mates, who are all gathered around and 'e says:",
	'',
	'',
	'Watch me wallabies feed, mate',
	'Watch me wallabies feed,',
	"They're a dangerous breed, mate",
	'So watch me wallabies feed',
	'Altogether now!',
	'',
	'CHORUS:',
	'Tie me kangaroo down, sport',
	'Tie me kangaroo down',
	'Tie me kangaroo down, sport',
	'Tie me kangaroo down',
	'',
	'Keep me cockatoo cool, Curl,',
	'Keep me cockatoo cool',
	"Ah, don't go acting the fool, Curl",
	'Just keep me cockatoo cool',
	'Altogether now!',
	'',
	'(CHORUS)',
	'',
	"'n' take me koala back, Jack",
	'Take me koala back',
	'He lives somewhere out on the track, Mac',
	'So take me koala back',
	'Altogether now!',
	'',
	'(CHORUS)',
	'',
	'Let me abos go loose, Lew',
	'Let me abos go loose',
	"They're of no further use, Lew",
	'So let me abos go loose',
	'Altogether now!',
	'',
	'(CHORUS)',
	'',
	'And mind me platypus duck, Bill',
	'Mind me platypus duck',
	"Ah, don't let 'im go running amok, Bill",
	'Just mind me platypus duck',
	'Altogether now!',
	'',
	'(CHORUS)',
	'',
	'Play your didgeridoo, Blue',
	'Play your didgeridoo',
	"Ah, like, keep playin' 'til I shoot thru, Blue",
	'Play your didgeridoo',
	'Altogether now!',
	'',
	'(CHORUS)',
	'',
	"Tan me hide when I'm dead, Fred",
	"Tan me hide when I'm dead",
	'So we tanned his hide when he died, Clyde',
	"And that's it hangin' on the shed!!",
	'Altogether now!',
	'',
	'(CHORUS)',
];

export default TieMeKangarooDownSport;
