const WalkingOnSunshine = [
	'Oh!',
	'',
	'Ohhhh, yeeeh',
	'',
	"I used to think maybe you loved me now baby I'm sure",
	"And I just can't wait till the day when you knock on my door",
	'Now everytime I go for the mailbox, gotta hold myself down',
	"'Cause I just can't wait till you write me you're coming around",
	'',
	"I'm walking on sunshine, wooah",
	"I'm walking on sunshine, woooah",
	"I'm walking on sunshine, woooah",
	"And don't it feel good!",
	'',
	'Hey, alright now',
	'And dont it feel good!',
	'Hey yeah',
	'',
	"I used to think maybe you loved me, now I know that it's true",
	"And I don't want to spend my whole life, just waiting for you",
	'',
	"Now I don't want u back for the weekend",
	'Not back for a day, no no no',
	'I said baby I just want you back and I want you to stay',
	'',
	'Woah yeah!',
	"I'm walking on sunshine, wooah",
	"I'm walking on sunshine, woooah",
	"I'm walking on sunshine, woooah",
	"And don't it feel good!!",
	'',
	'Hey, alright now',
	"And don't it feel good!!",
	'Yeah, oh yeah',
	"And don't it feel good!!",
	'',
	'Walking on sunshine',
	'Walking on sunshine',
	'',
	"I feel alive, I feel the love, I feel the love that's really real",
	"I feel alive, I feel the love, I feel the love that's really real",
	'',
	"I'm on sunshine baby oh, oh yeah",
	"I'm on sunshine baby oh",
	'',
	"I'm walking on sunshine, wooah",
	"I'm walking on sunshine, wooah",
	"I'm walking on sunshine, woooah",
	"And don't it feel good",
	'',
	'Hey, alright now',
	"And don't it feel good",
	'',
	"I'll say it, say it, say it again now",
	"And don't it feel good!!",
	'',
	'Ohhhh, yeahhhh',
	"And don't it feel good",
	"Now don't it, don't it, don't it, don't it, don't it, don't it feel good",
	'',
	"I'll say it, say it, say it again now",
	"And don't feel good",
	"Now don't it, don't it, don't it, don't it, don't it, don't it feel good",
	'',
	'Tell me, tell me, tell me again now',
	"And don't it feel good",
	'Ohhhh, yeahhhh',
	"And don't it feel good",
	"Oh don't it feel good, don't it feel good",
	"Now don't it feel good?",
	"Oh yeah, oh yeah, oh yeah (Don't it feel good)",
];

export default WalkingOnSunshine;
