const WhereHaveAllTheFlowersGone = [
	'Where have all the flowers gone, long time passing?',
	'Where have all the flowers gone, long time ago?',
	'Where have all the flowers gone?',
	'Young girls have picked them everyone.',
	'Oh, when will they ever learn?',
	'Oh, when will they ever learn?',
	'',
	'Where have all the young girls gone, long time passing?',
	'Where have all the young girls gone, long time ago?',
	'Where have all the young girls gone?',
	'Gone for husbands everyone.',
	'Oh, when will they ever learn?',
	'Oh, when will they ever learn?',
	'',
	'Where have all the husbands gone, long time passing?',
	'Where have all the husbands gone, long time ago?',
	'Where have all the husbands gone?',
	'Gone for soldiers everyone',
	'Oh, when will they ever learn?',
	'Oh, when will they ever learn?',
	'',
	'Where have all the soldiers gone, long time passing?',
	'Where have all the soldiers gone, long time ago?',
	'Where have all the soldiers gone?',
	'Gone to graveyards, everyone.',
	'Oh, when will they ever learn?',
	'Oh, when will they ever learn?',
	'',
	'Where have all the graveyards gone, long time passing?',
	'Where have all the graveyards gone, long time ago?',
	'Where have all the graveyards gone?',
	'Gone to flowers, everyone.',
	'Oh, when will they ever learn?',
	'Oh, when will they ever learn?',
	'',
	'Where have all the flowers gone, long time passing?',
	'Where have all the flowers gone, long time ago?',
	'Where have all the flowers gone?',
	'Young girls have picked them everyone.',
	'Oh, when will they ever learn?',
	'Oh, when will they ever learn?',
];

export default WhereHaveAllTheFlowersGone;
