export default {
	collectCoverage: true,
	collectCoverageFrom: [
		'src/**/*.{js,ts}',
		'!src/**/*.d.ts',
		'!src/**/const.ts',
		'!src/**/data.ts',
		'!src/**/interfaces/*',
		'!src/**/interfaces.ts',
		'!src/**/types.ts',
		'!src/**/*.const.ts',
		'!src/**/*.data.ts',
		'!src/**/*.interfaces.ts',
		'!src/**/*.mocks.ts',
		'!src/**/*.types.ts',
	],
	coverageDirectory: './jest-coverage',
	coverageReporters: ['json'],
	moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
	preset: 'ts-jest',
	testEnvironment: 'node',
	transformIgnorePatterns: ['node_modules', 'dist'],
};
