export default {
	collectCoverage: true,
	collectCoverageFrom: [
		'src/**/*.{js,ts}',
		'scripts/**/*.{js,ts}',
		// Built bundles, plus the entry scripts themselves - those run top to
		// bottom against a live page, so there is no unit to import.
		'!scripts/dist/**',
		'!scripts/ultimate-guitar-lyrics.ts',
		'!scripts/ultimate-guitar-print.ts',
		'!scripts/const.ts',
		'!scripts/**/*.const.ts',
		'!src/**/*.d.ts',
		'!src/**/const.ts',
		'!src/**/data.ts',
		'!src/**/interfaces/*',
		'!src/**/interfaces.ts',
		'!src/**/types.ts',
		'!src/**/*.const.ts',
		'!src/**/*.data.ts',
		'!src/**/*.interfaces.ts',
		'!src/**/*.mocks.ts',
		'!src/**/*.types.ts',
	],
	coverageDirectory: './jest-coverage',
	coverageReporters: ['json'],
	moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
	preset: 'ts-jest',
	testEnvironment: 'node',
	testPathIgnorePatterns: ['<rootDir>/dist'],
	transformIgnorePatterns: ['node_modules'],
};
