import * as GENRE from "./genres";
import LYRIC_LIST from "../components/lyrics";

module.exports = [
  {
    title: "All Through the Night",
    artist: "Misc Traditional",
    genres: [GENRE.TRADITIONAL],
    barChords: true,
    link: "https://tabs.ultimate-guitar.com/m/misc_traditional/all_through_the_night_crd.htm",
    lyrics: LYRIC_LIST.AllThroughTheNight,
  },
  {
    title: "America the Beautiful",
    artist: "Misc Traditional",
    genres: [GENRE.PATRIOTIC],
    link: "https://tabs.ultimate-guitar.com/m/misc_traditional/america_the_beautiful_crd.htm",
    lyrics: LYRIC_LIST.AmericaTheBeautiful,
  },
  {
    title: "Baby Baluga",
    artist: "Raffi Cavoukian",
    genres: [GENRE.KIDS],
    barChords: true,
    link: "https://tabs.ultimate-guitar.com/r/raffi/baby_beluga_crd.htm",
    lyrics: LYRIC_LIST.BabyBaluga,
  },
  {
    title: "Baby I Love Your Way",
    artist: "Peter Frampton",
    link: "https://tabs.ultimate-guitar.com/p/peter_frampton/baby_i_love_your_way_crd.htm",
    lyrics: LYRIC_LIST.BabyILoveYourWay,
  },
  {
    title: "Blowin' in the Wind",
    artist: "Bob Dylan",
    // link: "https://tabs.ultimate-guitar.com/b/bob_dylan/blowin_in_the_wind_ver10_crd_1086954id_25082011date.htm",
    lyrics: LYRIC_LIST.BlowinInTheWind,
  },
  {
    title: "Country Roads",
    artist: "John Denver",
    // link: "https://tabs.ultimate-guitar.com/j/john_denver/country_roads_ver2_crd.htm",
    lyrics: LYRIC_LIST.CountryRoads,
  },
  {
    title: "Edelweiss",
    artist: "Bob Carlisle",
    // link: "https://tabs.ultimate-guitar.com/s/sound_of_music/edelweiss_crd.htm",
    lyrics: LYRIC_LIST.Edelweiss,
  },
  {
    title: "Five Hundred Miles",
    artist: "Peter, Paul & Mary",
    link: "https://tabs.ultimate-guitar.com/p/peter_paul_and_mary/500_miles_crd.htm",
    lyrics: LYRIC_LIST.FiveHundredMiles,
  },
  {
    title: "God Bless the USA",
    artist: "Lee Greenwood",
    genres: [GENRE.PATRIOTIC],
    link: "https://tabs.ultimate-guitar.com/l/lee_greenwood/god_bless_the_usa_crd.htm",
    lyrics: LYRIC_LIST.GodBlessTheUSA,
  },
  {
    title: "He's Got the Whole World in His Hands",
    artist: "Misc Praise",
    genres: [GENRE.TRADITIONAL, GENRE.RELIGIOUS],
    link: "https://tabs.ultimate-guitar.com/m/misc_praise_songs/hes_got_the_whole_world_in_his_hands_crd.htm",
    lyrics: LYRIC_LIST.HesGotTheWholeWorldInHisHands,
  },
  {
    title: "Leaving on a Jet Plane",
    artist: "John Denver",
    // link: "https://tabs.ultimate-guitar.com/j/john_denver/leaving_on_a_jetplane_ver2_crd.htm",
    genres: [GENRE.ROCK],
    lyrics: LYRIC_LIST.LeavingOnAJetPlane,
  },
  {
    title: "Let there be Peace on Earth",
    artist: "Vince Gill",
    link: "https://tabs.ultimate-guitar.com/v/vince_gill/let_there_be_peace_on_earth_crd.htm",
    lyrics: LYRIC_LIST.LetThereBePeaceOnEarch,
  },
  {
    title: "Michael Finnegan",
    artist: "Misc Traditional",
    // link: "https://tabs.ultimate-guitar.com/m/misc_traditional/misc_traditional_-_michael_finnigan_crd.htm",
    genres: [GENRE.TRADITIONAL, GENRE.KIDS],
    lyrics: LYRIC_LIST.MichaelFinnegan,
  },
  {
    title: "Michael Row the Boat Ashore",
    artist: "Misc Traditional",
    // link: "https://tabs.ultimate-guitar.com/t/the_highwaymen/michael_row_the_boat_ashore_crd.htm",
    genres: [GENRE.TRADITIONAL],
    lyrics: LYRIC_LIST.MichaelRowTheBoatAshore,
  },
  {
    title: "Mockingbird",
    artist: "Misc Traditional",
    link: "https://tabs.ultimate-guitar.com/m/mother_goose/hush_little_baby_crd.htm",
    lyrics: LYRIC_LIST.Mockingbird,
  },
  {
    title: "Morning Has Broken",
    artist: "Cat Stevens",
    // link: "https://tabs.ultimate-guitar.com/c/cat_stevens/morning_has_broken_crd.htm",
    lyrics: LYRIC_LIST.MorningHasBroken,
  },
  {
    title: "Noah's Ark",
    artist: "Misc Children",
    genres: [GENRE.RELIGIOUS],
    link: "https://tabs.ultimate-guitar.com/m/misc_children/rise_and_shine_arky_arky_crd.htm",
    lyrics: LYRIC_LIST.NoahsArk,
  },
  {
    title: "One Tin Soldier",
    artist: "The Original Caste",
    // link: "https://tabs.ultimate-guitar.com/m/misc_unsigned_bands/the_original_caste_-_one_tin_soldier_crd.htm",
    lyrics: LYRIC_LIST.OneTinSoldier,
  },
  {
    title: "Over the Rainbow",
    artist: "Israel Kamakawiwo'ole",
    // link: "https://tabs.ultimate-guitar.com/i/israel_kamakawiwoole/somewhere_over_the_rainbow_crd.htm",
    lyrics: LYRIC_LIST.OverTheRainbow,
  },
  {
    title: "Puff The Magic Dragon",
    artist: "Peter, Paul & Mary",
    genres: [GENRE.FOLK, GENRE.KIDS],
    link: "https://tabs.ultimate-guitar.com/p/peter_paul_and_mary/puff_the_magic_dragon_ver3_crd.htm",
    lyrics: LYRIC_LIST.PuffTheMagicDragon,
  },
  {
    title: "Put Your Hand in the Hand",
    artist: "Anne Murray",
    link: "https://tabs.ultimate-guitar.com/a/anne_murray/put_your_hand_in_the_hand_ver2_crd.htm",
    lyrics: LYRIC_LIST.PutYourHandInTheHand,
  },
  {
    title: "Seattle",
    artist: "Perry Como",
    link: "http://www.classic-country-song-lyrics.com/seattlelyricschords.html",
    lyrics: LYRIC_LIST.Seattle,
  },
  {
    title: "Tell My Why",
    artist: "Misc Traditional",
    link: "https://tabs.ultimate-guitar.com/m/melanie/tell_me_why_crd.htm",
    lyrics: LYRIC_LIST.TellMeWhy,
  },
  {
    title: "The Cat Came Back",
    artist: "Harry S Miller",
    genres: [GENRE.KIDS],
    link: "https://tabs.ultimate-guitar.com/h/harry_s_miller/the_cat_came_back_crd.htm",
    lyrics: LYRIC_LIST.TheCatCameBack,
  },
  {
    title: "The Sounds of Silence",
    artist: "Simon & Garfunkel",
    genres: [GENRE.FOLK],
    link: "https://tabs.ultimate-guitar.com/s/simon_garfunkel/the_sound_of_silence_ver4_crd.htm",
    lyrics: LYRIC_LIST.TheSoundsOfSilence,
  },
  {
    title: "This Land is your Land",
    artist: "Woody Guthrie",
    genres: [GENRE.PATRIOTIC],
    link: "http://www.guitaretab.com/w/woody-guthrie/223617.html",
    lyrics: LYRIC_LIST.ThisLandIsYourLand,
  },
  {
    title: "Tie Me Kangaroo Down Sport",
    artist: "Rolf Harris",
    genres: [GENRE.KIDS],
    link: "https://tabs.ultimate-guitar.com/r/rolf_harris/tie_me_kangaroo_down_sport_ver4_crd.htm",
    lyrics: LYRIC_LIST.TieMeKangarooDownSport,
  },
  {
    title: 'Turn" Turn" Turn',
    artist: "The Byrds",
    genres: [GENRE.FOLK],
    lyrics: LYRIC_LIST.TurnTurnTurn,
  },
  {
    title: "Wedding Song",
    artist: "Paul Stookey",
    lyrics: LYRIC_LIST.WeddingSong,
  },
  {
    title: "What Child is This",
    artist: "Misc Christmas",
    link: "https://tabs.ultimate-guitar.com/m/misc_christmas/what_child_is_this_crd.htm",
    lyrics: LYRIC_LIST.WhatChildIsThis,
  },
  {
    title: "What the World Needs Now is Love",
    artist: "Diana Ross",
    link: "https://tabs.ultimate-guitar.com/j/jackie_deshannon/what_the_world_needs_now_is_love_crd.htm",
    lyrics: LYRIC_LIST.WhatTheWorldNeedsNowIsLove,
  },
  {
    title: "Where Have All the Flowers Gone",
    artist: "Pete Seeger",
    genres: [GENRE.FOLK],
    link: "https://tabs.ultimate-guitar.com/p/peter_paul_and_mary/where_have_all_the_flowers_gone_ver2_crd.htm",
    lyrics: LYRIC_LIST.WhereHaveAllTheFlowersGone,
  },
  {
    title: "Yellow Submarine",
    artist: "The Beatles",
    link: "https://tabs.ultimate-guitar.com/t/the_beatles/yellow_submarine_ver2_crd.htm",
    lyrics: LYRIC_LIST.YellowSubmarine,
  },
  {
    title: "You Are My Sunshine",
    artist: "Chris Stapleton",
    genres: [GENRE.TRADITIONAL],
    // link: "https://tabs.ultimate-guitar.com/c/chris_stapleton/you_are_my_sunshine_crd.htm",
    lyrics: LYRIC_LIST.YouAreMySunshine,
  },
];
