import * as ERAS from './eras';
import * as GENRES from './genres';
import LYRIC_LIST from '../lyrics';
import { SongType } from '../types';

const CAPO_2 = 'Capo 2';
const CAPO_3 = 'Capo 3';
const CAPO_5 = 'Capo 5';

export const SongList: SongType[] = [
	// - A -
	{
		artist: 'America',
		eras: [ERAS.SEVENTIES],
		genres: [GENRES.FOLK, GENRES.ROCK],
		link: 'https://tabs.ultimate-guitar.com/tab/america/a-horse-with-no-name-chords-1042336',
		lyrics: LYRIC_LIST.AHorseWithNoName,
		title: 'A Horse With No Name',
	},
	// - B -
	{
		artist: 'Raffi Cavoukian',
		barChords: true,
		eras: [ERAS.EIGHTIES],
		genres: [GENRES.KIDS],
		link: 'https://tabs.ultimate-guitar.com/r/raffi/baby_beluga_crd.htm',
		lyrics: LYRIC_LIST.BabyBaluga,
		title: 'Baby Baluga',
	},
	{
		artist: 'Peter Frampton',
		barChords: true,
		eras: [ERAS.NINETIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/p/peter_frampton/baby_i_love_your_way_crd.htm',
		lyrics: LYRIC_LIST.BabyILoveYourWay,
		title: 'Baby I Love Your Way',
	},
	{
		artist: 'Andy Grammer',
		eras: [ERAS.TWENTY_TENS],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/andy-grammer/back-home-chords-1479557',
		lyrics: LYRIC_LIST.BackHome,
		title: 'Back Home',
	},
	{
		artist: 'Bob Dylan',
		eras: [ERAS.SIXTIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/bob-dylan/blowin-in-the-wind-chords-14835',
		lyrics: LYRIC_LIST.BlowinInTheWind,
		title: "Blowin' in the Wind",
	},
	{
		artist: 'Bob Carlisle',
		barChords: true,
		eras: [ERAS.NINETIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/bob-carlisle/butterfly-kisses-chords-64393',
		lyrics: LYRIC_LIST.ButterflyKisses,
		title: 'Butterfly Kisses',
	},
	// - C -
	{
		alteration: CAPO_2,
		artist: 'Semisonic',
		eras: [ERAS.NINETIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/semisonic/closing-time-chords-1743417',
		lyrics: LYRIC_LIST.ClosingTime,
		title: 'Closing Time',
	},
	{
		artist: 'John Denver',
		eras: [ERAS.SEVENTIES],
		genres: [GENRES.COUNTRY],
		link: 'https://tabs.ultimate-guitar.com/tab/john-denver/take-me-home-country-roads-chords-1101747',
		lyrics: LYRIC_LIST.CountryRoads,
		title: 'Country Roads',
	},
	// - D -
	{
		artist: 'Journey',
		barChords: true,
		eras: [ERAS.EIGHTIES],
		genres: [GENRES.ROCK],
		link: 'https://tabs.ultimate-guitar.com/tab/journey/dont-stop-believin-chords-275297',
		lyrics: LYRIC_LIST.DontStopBelievin,
		title: "Don't Stop Believin'",
	},
	// - F -
	{
		artist: 'Randy Travis',
		eras: [ERAS.EIGHTIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/randy-travis/forever-and-ever-amen-chords-87134',
		lyrics: LYRIC_LIST.ForeverAndEverAmen,
		title: 'Forever And Ever Amen',
	},
	{
		artist: 'Tom Petty',
		eras: [ERAS.EIGHTIES],
		genres: [],
		link: 'https://www.chordie.com/chord.pere/www.guitaretab.com/p/petty-tom/14472.html',
		lyrics: LYRIC_LIST.FreeFallin,
		title: 'Free Fallin',
	},
	// - G -
	{
		artist: "Plain White T's",
		eras: [ERAS.TWENTY_TENS],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/plain-white-ts/the-giving-tree-chords-1240804',
		lyrics: LYRIC_LIST.GivingTree,
		title: 'Giving Tree',
	},
	{
		artist: 'Lee Greenwood',
		barChords: true,
		eras: [ERAS.EIGHTIES],
		genres: [GENRES.PATRIOTIC],
		link: 'https://tabs.ultimate-guitar.com/tab/lee-greenwood/god-bless-the-usa-chords-825566',
		lyrics: LYRIC_LIST.GodBlessTheUSA,
		title: 'God Bless the USA',
	},
	{
		alteration: CAPO_5,
		artist: 'Kane Brown',
		eras: [ERAS.TWENTY_TENS],
		genres: [GENRES.COUNTRY],
		link: 'https://tabs.ultimate-guitar.com/tab/kane-brown/good-as-you-chords-2497455',
		lyrics: LYRIC_LIST.GoodAsYou,
		title: 'Good As You',
		// https://tabs.ultimate-guitar.com/tab/kane-brown/good-as-you-chords-2497455
	},
	// - H -
	{
		artist: 'Misc Praise',
		eras: [],
		genres: [GENRES.TRADITIONAL, GENRES.SOUL],
		link: 'https://tabs.ultimate-guitar.com/m/misc_praise_songs/hes_got_the_whole_world_in_his_hands_crd.htm',
		lyrics: LYRIC_LIST.HesGotTheWholeWorldInHisHands,
		title: "He's Got the Whole World in His Hands",
	},
	{
		artist: 'Misc Traditional',
		eras: [ERAS.EIGHTEEN_SEVENTIES],
		genres: [GENRES.WESTERN, GENRES.FOLK],
		link: 'https://tabs.ultimate-guitar.com/tab/misc-traditional/home-on-the-range-chords-1726287',
		lyrics: LYRIC_LIST.HomeOnTheRange,
		title: 'Home On The Range',
	},
	{
		alteration: CAPO_5,
		artist: 'Kenny Loggins',
		barChords: true,
		eras: [ERAS.SEVENTIES],
		genres: [GENRES.KIDS],
		link: 'https://qcukes.com/music2/music.php?action=Song&song=House%20At%20Pooh%20Corner',
		lyrics: LYRIC_LIST.HouseAtPoohCorner,
		title: 'House At Pooh Corner',
		// https://www.youtube.com/watch?v=hWBE9YCC0Oc
	},
	// - I -
	{
		artist: 'Bonnie Raitt',
		eras: [ERAS.NINETIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/bonnie-raitt/i-cant-make-you-love-me-chords-611294',
		lyrics: LYRIC_LIST.ICantMakeYouLoveMe,
		title: 'I Cant Make You Love Me',
	},
	{
		artist: 'Burl Ives',
		barChords: true,
		eras: [ERAS.FIFTIES],
		genres: [GENRES.KIDS, GENRES.FOLK],
		link: 'https://tabs.ultimate-guitar.com/tab/burl-ives/i-know-an-old-lady-who-swallowed-a-fly-chords-674886',
		lyrics: LYRIC_LIST.IKnowAnOldLadyWhoSwallowedAFly,
		title: 'I Know An Old Lady Who Swallowed A Fly',
	},
	{
		artist: 'Tim McGraw',
		eras: [ERAS.NINETIES],
		genres: [GENRES.COUNTRY],
		link: 'https://tabs.ultimate-guitar.com/tab/tim-mcgraw/its-your-love-chords-76292',
		lyrics: LYRIC_LIST.ItsYourLove,
		strumPattern: 'DxDxDxDU',
		title: "It's Your Love",
		// https://www.youtube.com/watch?v=BOibmAAqWuo
	},
	// - J -
	{
		alteration: CAPO_3,
		artist: 'Third Eye Blind',
		eras: [ERAS.NINETIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/third-eye-blind/jumper-chords-159256',
		lyrics: LYRIC_LIST.Jumper,
		title: 'Jumper',
	},
	// - K -
	{
		artist: 'Marion Sinclair',
		barChords: true,
		eras: [ERAS.THIRTIES],
		genres: [GENRES.FOLK, GENRES.KIDS],
		link: 'https://tabs.ultimate-guitar.com/tab/marion-sinclair/kookaburra-chords-1048595',
		lyrics: LYRIC_LIST.Kookaburra,
		title: 'Kookaburra',
	},
	{
		artist: 'Misc Praise',
		eras: [ERAS.TWENTIES],
		genres: [GENRES.FOLK, GENRES.SOUL],
		link: 'https://tabs.ultimate-guitar.com/tab/misc-praise-songs/kumbaya-chords-76633',
		lyrics: LYRIC_LIST.Kumbaya,
		title: 'Kumbaya',
	},
	// - L -
	{
		artist: 'Bill Withers',
		barChords: true,
		eras: [ERAS.SEVENTIES],
		genres: [GENRES.R_AND_B, GENRES.SOUL],
		link: 'https://tabs.ultimate-guitar.com/tab/bill-withers/lean-on-me-chords-150987',
		lyrics: LYRIC_LIST.LeanOnMe,
		title: 'Lean On Me',
	},
	{
		artist: 'John Denver',
		eras: [ERAS.SIXTIES],
		genres: [GENRES.ROCK],
		link: 'https://www.laurenbateman.com/leaving-on-a-jet-plane-chord-chart',
		lyrics: LYRIC_LIST.LeavingOnAJetPlane,
		title: 'Leaving on a Jet Plane',
	},
	// - M -
	{
		artist: 'Rod Stewart',
		barChords: true,
		eras: [ERAS.SEVENTIES],
		genres: [GENRES.ROCK, GENRES.FOLK],
		link: 'https://tabs.ultimate-guitar.com/tab/rod-stewart/maggie-may-chords-85329',
		lyrics: LYRIC_LIST.MaggieMay,
		title: 'Maggie May',
	},
	{
		artist: 'Adele',
		eras: [ERAS.TWO_THOUSANDS],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/adele/make-you-feel-my-love-chords-752102',
		lyrics: LYRIC_LIST.MakeYouFeelMyLove,
		strumPattern: '[Rock Strum] DxDUxUDU',
		title: 'Make You Feel My Love',
	},
	{
		artist: 'Misc Traditional',
		eras: [],
		genres: [GENRES.TRADITIONAL, GENRES.KIDS],
		link: 'https://tabs.ultimate-guitar.com/tab/misc-children/michael-finnegan-chords-1721165',
		lyrics: LYRIC_LIST.MichaelFinnegan,
		title: 'Michael Finnegan',
	},
	{
		artist: 'Misc Traditional',
		barChords: true,
		eras: [],
		genres: [GENRES.TRADITIONAL],
		link: 'https://tabs.ultimate-guitar.com/tab/highwaymen/michael-row-the-boat-ashore-chords-1813491',
		lyrics: LYRIC_LIST.MichaelRowTheBoatAshore,
		title: 'Michael Row the Boat Ashore',
	},
	{
		artist: 'Misc Traditional',
		eras: [],
		genres: [GENRES.TRADITIONAL],
		link: 'https://tabs.ultimate-guitar.com/m/mother_goose/hush_little_baby_crd.htm',
		lyrics: LYRIC_LIST.Mockingbird,
		title: 'Mockingbird',
	},
	{
		artist: 'Misc Traditional',
		eras: [ERAS.EIGHTEEN_EIGHTIES],
		genres: [GENRES.FOLK],
		link: 'https://tabs.ultimate-guitar.com/tab/misc-traditional/my-bonnie-lies-over-the-ocean-chords-973976',
		lyrics: LYRIC_LIST.MyBonnieLiesOverTheOcean,
		title: 'My Bonnie Lies Over The Ocean',
	},
	// - N -
	{
		artist: 'One Direction',
		barChords: true,
		eras: [ERAS.TWENTY_TENS],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/one-direction/night-changes-chords-1678440',
		lyrics: LYRIC_LIST.NightChanges,
		title: 'Night Changes',
	},
	// - O -
	{
		artist: 'Misc Traditional',
		eras: [ERAS.EIGHTEEN_FOURTIES],
		genres: [GENRES.FOLK],
		link: 'https://tabs.ultimate-guitar.com/tab/misc-traditional/oh-susanna-chords-1050965',
		lyrics: LYRIC_LIST.OhSusanna,
		title: 'Oh Susanna',
	},
	{
		artist: 'Misc Children',
		eras: [ERAS.SIXTIES],
		genres: [GENRES.KIDS, GENRES.FOLK],
		link: 'https://tabs.ultimate-guitar.com/tab/misc-children/on-top-of-spaghetti-chords-1404074',
		lyrics: LYRIC_LIST.OnTopOfSpaghetti,
		title: 'On Top Of Spaghetti',
	},
	{
		artist: 'The Original Caste',
		barChords: true,
		eras: [ERAS.SIXTIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/the-original-caste/one-tin-soldier-chords-980986',
		lyrics: LYRIC_LIST.OneTinSoldier,
		title: 'One Tin Soldier',
	},
	{
		artist: "Israel Kamakawiwo'ole",
		barChords: true,
		eras: [ERAS.NINETIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/2135261',
		lyrics: LYRIC_LIST.OverTheRainbow,
		title: 'Over the Rainbow',
	},
	// - P -
	{
		artist: 'Peter, Paul & Mary',
		barChords: true,
		eras: [ERAS.SIXTIES],
		genres: [GENRES.FOLK, GENRES.KIDS],
		link: 'https://tabs.ultimate-guitar.com/p/peter_paul_and_mary/puff_the_magic_dragon_ver3_crd.htm',
		lyrics: LYRIC_LIST.PuffTheMagicDragon,
		title: 'Puff The Magic Dragon',
	},
	// - R -
	{
		artist: 'Richard Marx',
		barChords: true,
		eras: [ERAS.EIGHTIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/richard-marx/right-here-waiting-chords-93388',
		lyrics: LYRIC_LIST.RightHereWaiting,
		title: 'Right Here Waiting',
	},
	// - S -
	{
		artist: 'Misc Traditional',
		eras: [ERAS.TWENTIES],
		genres: [GENRES.KIDS, GENRES.FOLK],
		link: 'https://tabs.ultimate-guitar.com/tab/misc-traditional/shell-be-coming-round-the-mountain-chords-1178525',
		lyrics: LYRIC_LIST.ShellBeComingRoundTheMountain,
		title: "She'll Be Coming Round The Mountain",
	},
	{
		artist: 'Otis Redding',
		eras: [ERAS.SIXTIES],
		genres: [GENRES.R_AND_B],
		link: 'https://tabs.ultimate-guitar.com/tab/otis-redding/sittin-on-the-dock-of-the-bay-chords-81840',
		lyrics: LYRIC_LIST.SittinOnTheDockOfTheBay,
		title: 'Sittin On The Dock Of The Bay',
	},
	{
		artist: 'Ben E. King',
		barChords: true,
		eras: [ERAS.SIXTIES],
		genres: [GENRES.R_AND_B, GENRES.SOUL],
		link: 'https://tabs.ultimate-guitar.com/tab/ben-e-king/stand-by-me-chords-73005',
		lyrics: LYRIC_LIST.StandByMe,
		title: 'Stand By Me',
	},
	{
		artist: 'Jonathan Edwards',
		eras: [ERAS.SEVENTIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/jonathan-edwards/sunshine-chords-105167',
		lyrics: LYRIC_LIST.Sunshine,
		title: 'Sunshine',
	},
	// - T -
	{
		artist: 'Eagles',
		eras: [ERAS.SEVENTIES],
		genres: [GENRES.ROCK],
		link: 'https://tabs.ultimate-guitar.com/tab/eagles/take-it-easy-chords-14303',
		lyrics: LYRIC_LIST.TakeItEasy,
		title: 'Take It Easy',
	},
	{
		artist: 'Eric Clapton',
		barChords: true,
		eras: [ERAS.NINETIES],
		genres: [GENRES.R_AND_B],
		link: 'https://www.guitartabsexplorer.com/clapton-eric-Tabs/tears-in-heaven-live-crd.php',
		lyrics: LYRIC_LIST.TearsInHeaven,
		strumPattern: 'DxDU, DxDU, DxDU UDUDD',
		title: 'Tears In Heaven',
	},
	// {
	// 	artist: 'Harry S Miller',
	// 	genres: [GENRES.KIDS],
	// 	link: 'https://tabs.ultimate-guitar.com/h/harry_s_miller/the_cat_came_back_crd.htm',
	// 	lyrics: LYRIC_LIST.TheCatCameBack,
	// 	title: 'The Cat Came Back',
	// },
	{
		artist: 'Simon & Garfunkel',
		barChords: true,
		eras: [ERAS.SIXTIES],
		genres: [GENRES.FOLK],
		link: 'https://tabs.ultimate-guitar.com/s/simon_garfunkel/the_sound_of_silence_ver4_crd.htm',
		lyrics: LYRIC_LIST.TheSoundOfSilence,
		title: 'The Sounds of Silence',
	},
	{
		artist: 'Woody Guthrie',
		eras: [ERAS.FOURTIES],
		genres: [GENRES.PATRIOTIC],
		link: 'http://www.guitaretab.com/w/woody-guthrie/223617.html',
		lyrics: LYRIC_LIST.ThisLandIsYourLand,
		title: 'This Land is your Land',
	},
	{
		artist: 'Rolf Harris',
		eras: [ERAS.SIXTIES],
		genres: [GENRES.KIDS],
		link: 'https://tabs.ultimate-guitar.com/r/rolf_harris/tie_me_kangaroo_down_sport_ver4_crd.htm',
		lyrics: LYRIC_LIST.TieMeKangarooDownSport,
		title: 'Tie Me Kangaroo Down Sport',
	},
	{
		artist: 'The Byrds',
		barChords: true,
		eras: [ERAS.SIXTIES],
		genres: [GENRES.FOLK],
		link: 'https://tabs.ultimate-guitar.com/tab/the-byrds/turn-turn-turn-to-everything-there-is-a-season-chords-1055233',
		lyrics: LYRIC_LIST.TurnTurnTurn,
		title: 'Turn" Turn" Turn',
	},
	// - W -
	{
		artist: 'Katrina and the Waves',
		eras: [ERAS.EIGHTIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/katrina-and-the-waves/walking-on-sunshine-chords-595283',
		lyrics: LYRIC_LIST.WalkingOnSunshine,
		title: 'Walking On Sunshine',
	},
	{
		alteration: 'Only sing on Choras. The other parts are more like chants',
		artist: 'Jackie DeShannon',
		barChords: true,
		eras: [ERAS.SIXTIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/j/jackie_deshannon/what_the_world_needs_now_is_love_crd.htm',
		lyrics: LYRIC_LIST.WhatTheWorldNeedsNowIsLove,
		title: 'What the World Needs Now is Love',
	},
	{
		artist: 'Pete Seeger',
		barChords: true,
		eras: [ERAS.SIXTIES],
		genres: [GENRES.FOLK],
		link: 'https://tabs.ultimate-guitar.com/p/peter_paul_and_mary/where_have_all_the_flowers_gone_ver2_crd.htm',
		lyrics: LYRIC_LIST.WhereHaveAllTheFlowersGone,
		title: 'Where Have All the Flowers Gone',
	},
	{
		artist: 'U2',
		barChords: true,
		eras: [ERAS.EIGHTIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/u2/with-or-without-you-chords-835',
		lyrics: LYRIC_LIST.WithOrWithoutYou,
		title: 'With Or Without You',
	},
	// - Y -
	{
		artist: 'The Beatles',
		eras: [ERAS.SIXTIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/t/the_beatles/yellow_submarine_ver2_crd.htm',
		lyrics: LYRIC_LIST.YellowSubmarine,
		title: 'Yellow Submarine',
	},
	{
		artist: 'Chris Stapleton',
		eras: [],
		genres: [GENRES.TRADITIONAL],
		link: 'https://tabs.ultimate-guitar.com/tab/morgane-stapleton/you-are-my-sunshine-chords-1843946',
		lyrics: LYRIC_LIST.YouAreMySunshine,
		title: 'You Are My Sunshine',
	},
	{
		artist: 'Shania Twain',
		eras: [ERAS.NINETIES],
		genres: [],
		link: 'https://tabs.ultimate-guitar.com/tab/shania-twain/youre-still-the-one-chords-1345',
		lyrics: LYRIC_LIST.YoureStillTheOne,
		title: "You're Still The One",
	},
];
