#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#-- Functions

function printTitle() {
    echo "\n==================== Git Push ===================="
}

function printSectionTitle() {
    echo "\n---------- $1 ----------\n"
}

#-- Run

printTitle

printSectionTitle "Typescripting"
yarn ts-check